name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      # Install Dependencies
      # npm ci is similar to npm install but it's more suitable for CI environments
      - run: npm ci

      # Check code formatting
      - run: npm run format:check

      # Run automated tests
      - run: npm test -- --coverage
        env:
          # Required so that tests are run non-interactively:
          CI: true
      # Upload Code Coverage as an Artifact
      # Cache Dependencies
